# 01 — Preparação dos Dados da RAIS 2025

## Objetivo

Este notebook realiza a leitura, seleção, limpeza e preparação dos
microdados da RAIS 2025 referentes ao estado de São Paulo.

A análise tem como foco investigar a associação entre escolaridade e
remuneração dos vínculos formais e verificar como essa relação varia
entre os setores de atividade econômica.

## Fonte

- Base: Relação Anual de Informações Sociais (RAIS)
- Ano-base: 2025
- Fonte: Ministério do Trabalho e Emprego (MTE)
- Arquivo: `RAIS_VINC_PUB_SP.COMT`
- Unidade de análise: vínculo empregatício formal

In [3]:
import pandas as pd
from pathlib import Path

In [4]:
DATA_RAW = Path("../data/raw")
DATA_PROCESSED = Path("../data/processed")

arquivo_rais = DATA_RAW / "RAIS_VINC_PUB_SP.COMT"

In [5]:
arquivo_rais.exists()

True

In [6]:
tamanho_gb = arquivo_rais.stat().st_size / (1024 ** 3)

print(f"Tamanho do arquivo: {tamanho_gb:.2f} GB")

Tamanho do arquivo: 6.38 GB

In [7]:
amostra = pd.read_csv(
    arquivo_rais,
    sep=",",
    encoding="latin1",
    nrows=5
)

amostra

,Bairros SP - Código,Bairros Fortaleza - Código,Bairros RJ - Código,Causa Afastamento 1 - Código,Causa Afastamento 2 - Código,Causa Afastamento 3 - Código,Motivo Desligamento - Código,CBO 2002 Ocupação - Código,CNAE 2.0 Classe - Código,CNAE 95 Classe - Código,...,Vl Rem Julho SC,Vl Rem Agosto SC,Vl Rem Setembro SC,Vl Rem Outubro SC,Vl Rem Novembro SC,Ano Chegada Brasil,Ind Trabalho Intermitente - Código,Ind Trabalho Parcial - Código,Ind Vínculo Abandonado - Código,Categoria Trabalhador - Código
0,999997,999997,999997,999,999,999,0,911305,33147,29947,...,0,0,0,0,0,1198,1,0,0,111
1,999997,999997,999997,999,999,999,0,142330,64638,65994,...,0,0,0,0,0,1198,0,0,1,101
2,999997,999997,999997,999,999,999,0,521110,47814,52329,...,0,0,0,0,0,1198,0,0,0,101
3,999997,999997,999997,999,999,999,31,414105,38114,90000,...,0,0,0,0,0,1198,0,0,0,101
4,999997,999997,999997,10,999,999,0,514225,42227,45292,...,0,0,0,0,0,1198,0,0,0,101

In [8]:
amostra.columns.tolist()

['Bairros SP - Código',
 'Bairros Fortaleza - Código',
 'Bairros RJ - Código',
 'Causa Afastamento 1 - Código',
 'Causa Afastamento 2 - Código',
 'Causa Afastamento 3 - Código',
 'Motivo Desligamento - Código',
 'CBO 2002 Ocupação - Código',
 'CNAE 2.0 Classe - Código',
 'CNAE 95 Classe - Código',
 'Distritos SP - Código',
 'Ind Vínculo Ativo 31/12 - Código',
 'Faixa Etária - Código',
 'Faixa Rem Média (SM) - Código',
 'Faixa Hora Contrat - Código',
 'Faixa Rem Dez (SM) - Código',
 'Faixa Tempo Emprego - Código',
 'Escolaridade Após 2005 - Código',
 'Qtd Hora Contr',
 'Idade',
 'Ind CEI Vinculado - Código',
 'Ind Estabelecimento Participante SIMPLES - Código',
 'Mês Admissão - Código',
 'Mês Desligamento - Código',
 'Município Trab - Código',
 'Município - Código',
 'Nacionalidade - Código',
 'Natureza Jurídica - Código',
 'Ind Portador Defic - Código',
 'Qtd Dias Afastamento',
 'Raça Cor - Código',
 'Região Adm DF - Código',
 'Vl Rem Dezembro Nom',
 'Vl Rem Dezembro (SM)',
 'Vl Rem Média Nom',
 'Vl Rem Média (SM)',
 'CNAE 2.0 Subclasse - Codigo',
 'Sexo - Código',
 'Tamanho Estabelecimento - Código',
 'Tempo Emprego',
 'Tipo Admissão Trabalhador - Código',
 'Tipo Estabelecimento - Código',
 'Tipo Estabelecimento - Nome',
 'Tipo Deficiência - Código',
 'Tipo Vínculo - Código',
 'IBGE Subsetor - Código',
 'Vl Rem Janeiro SC',
 'Vl Rem Fevereiro SC',
 'Vl Rem Março SC',
 'Vl Rem Abril SC',
 'Vl Rem Maio SC',
 'Vl Rem Junho SC',
 'Vl Rem Julho SC',
 'Vl Rem Agosto SC',
 'Vl Rem Setembro SC',
 'Vl Rem Outubro SC',
 'Vl Rem Novembro SC',
 'Ano Chegada Brasil',
 'Ind Trabalho Intermitente - Código',
 'Ind Trabalho Parcial - Código',
 'Ind Vínculo Abandonado - Código',
 'Categoria Trabalhador - Código']

In [9]:
amostra.dtypes

Bairros SP - Código                   int64
Bairros Fortaleza - Código            int64
Bairros RJ - Código                   int64
Causa Afastamento 1 - Código          int64
Causa Afastamento 2 - Código          int64
                                      ...
Ano Chegada Brasil                    int64
Ind Trabalho Intermitente - Código    int64
Ind Trabalho Parcial - Código         int64
Ind Vínculo Abandonado - Código       int64
Categoria Trabalhador - Código        int64
Length: 62, dtype: object

In [10]:
amostra.head()

,Bairros SP - Código,Bairros Fortaleza - Código,Bairros RJ - Código,Causa Afastamento 1 - Código,Causa Afastamento 2 - Código,Causa Afastamento 3 - Código,Motivo Desligamento - Código,CBO 2002 Ocupação - Código,CNAE 2.0 Classe - Código,CNAE 95 Classe - Código,...,Vl Rem Julho SC,Vl Rem Agosto SC,Vl Rem Setembro SC,Vl Rem Outubro SC,Vl Rem Novembro SC,Ano Chegada Brasil,Ind Trabalho Intermitente - Código,Ind Trabalho Parcial - Código,Ind Vínculo Abandonado - Código,Categoria Trabalhador - Código
0,999997,999997,999997,999,999,999,0,911305,33147,29947,...,0,0,0,0,0,1198,1,0,0,111
1,999997,999997,999997,999,999,999,0,142330,64638,65994,...,0,0,0,0,0,1198,0,0,1,101
2,999997,999997,999997,999,999,999,0,521110,47814,52329,...,0,0,0,0,0,1198,0,0,0,101
3,999997,999997,999997,999,999,999,31,414105,38114,90000,...,0,0,0,0,0,1198,0,0,0,101
4,999997,999997,999997,10,999,999,0,514225,42227,45292,...,0,0,0,0,0,1198,0,0,0,101

In [11]:
print(f"Linhas: {amostra.shape[0]}")
print(f"Colunas: {amostra.shape[1]}")

Linhas: 5
Colunas: 62

In [12]:
colunas = [
    "Ind Vínculo Ativo 31/12 - Código",
    "Escolaridade Após 2005 - Código",
    "Vl Rem Dezembro Nom",
    "CNAE 2.0 Classe - Código",
    "CNAE 2.0 Subclasse - Codigo",
    "Idade",
    "Sexo - Código",
    "Tipo Vínculo - Código",
    "CBO 2002 Ocupação - Código",
    "Qtd Hora Contr",
    "Tempo Emprego",
    "Tamanho Estabelecimento - Código"
]

In [13]:
amostra_selecionada = amostra[colunas]

amostra_selecionada

,Ind Vínculo Ativo 31/12 - Código,Escolaridade Após 2005 - Código,Vl Rem Dezembro Nom,CNAE 2.0 Classe - Código,CNAE 2.0 Subclasse - Codigo,Idade,Sexo - Código,Tipo Vínculo - Código,CBO 2002 Ocupação - Código,Qtd Hora Contr,Tempo Emprego,Tamanho Estabelecimento - Código
0,1,7,NaN,33147,3314713,34,1,10,911305,99,18.9,8
1,1,9,NaN,64638,6463800,41,2,10,142330,40,59.0,4
2,1,7,NaN,47814,4781400,44,2,10,521110,44,26.0,3
3,0,7,NaN,38114,3811400,53,1,10,414105,44,20.9,6
4,1,4,NaN,42227,4222701,48,1,10,514225,44,38.9,3

In [14]:
amostra_selecionada.dtypes

Ind Vínculo Ativo 31/12 - Código      int64
Escolaridade Após 2005 - Código       int64
Vl Rem Dezembro Nom                 float64
CNAE 2.0 Classe - Código              int64
CNAE 2.0 Subclasse - Codigo           int64
Idade                                 int64
Sexo - Código                         int64
Tipo Vínculo - Código                 int64
CBO 2002 Ocupação - Código            int64
Qtd Hora Contr                        int64
Tempo Emprego                       float64
Tamanho Estabelecimento - Código      int64
dtype: object

In [15]:
amostra_selecionada.T

,0,1,2,3,4
Ind Vínculo Ativo 31/12 - Código,1.0,1.0,1.0,0.0,1.0
Escolaridade Após 2005 - Código,7.0,9.0,7.0,7.0,4.0
Vl Rem Dezembro Nom,NaN,NaN,NaN,NaN,NaN
CNAE 2.0 Classe - Código,33147.0,64638.0,47814.0,38114.0,42227.0
CNAE 2.0 Subclasse - Codigo,3314713.0,6463800.0,4781400.0,3811400.0,4222701.0
Idade,34.0,41.0,44.0,53.0,48.0
Sexo - Código,1.0,2.0,2.0,1.0,1.0
Tipo Vínculo - Código,10.0,10.0,10.0,10.0,10.0
CBO 2002 Ocupação - Código,911305.0,142330.0,521110.0,414105.0,514225.0
Qtd Hora Contr,99.0,40.0,44.0,44.0,44.0
Tempo Emprego,18.9,59.0,26.0,20.9,38.9
Tamanho Estabelecimento - Código,8.0,4.0,3.0,6.0,3.0

In [16]:
amostra_10k = pd.read_csv(
    arquivo_rais,
    sep=",",
    encoding="latin1",
    usecols=colunas,
    nrows=10_000
)

amostra_10k.shape

(10000, 12)

In [17]:
amostra_10k.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   CBO 2002 Ocupação - Código        10000 non-null  int64
 1   CNAE 2.0 Classe - Código          10000 non-null  int64
 2   Ind Vínculo Ativo 31/12 - Código  10000 non-null  int64
 3   Escolaridade Após 2005 - Código   10000 non-null  int64
 4   Qtd Hora Contr                    10000 non-null  int64
 5   Idade                             10000 non-null  int64
 6   Vl Rem Dezembro Nom               2603 non-null   float64
 7   CNAE 2.0 Subclasse - Codigo       10000 non-null  int64
 8   Sexo - Código                     10000 non-null  int64
 9   Tamanho Estabelecimento - Código  10000 non-null  int64
 10  Tempo Emprego                     10000 non-null  float64
 11  Tipo Vínculo - Código             10000 non-null  int64
dtypes: float64(2), int64(10)
memory usage: 937.6 KB

In [18]:
amostra_10k[
    [
        "Ind Vínculo Ativo 31/12 - Código",
        "Escolaridade Após 2005 - Código",
        "Vl Rem Dezembro Nom"
    ]
].head(20)

,Ind Vínculo Ativo 31/12 - Código,Escolaridade Após 2005 - Código,Vl Rem Dezembro Nom
0,1,7,NaN
1,1,9,NaN
2,1,7,NaN
3,0,7,NaN
4,1,4,NaN
5,1,7,NaN
6,0,7,NaN
7,1,9,NaN
8,1,7,NaN
9,1,7,NaN
10,1,7,NaN
11,0,7,NaN
12,0,7,NaN
13,0,6,NaN
14,1,7,NaN
15,1,7,NaN
16,1,5,NaN
17,1,5,NaN
18,1,9,NaN
19,0,7,NaN

In [19]:
amostra_10k.isna().sum()

CBO 2002 Ocupação - Código             0
CNAE 2.0 Classe - Código               0
Ind Vínculo Ativo 31/12 - Código       0
Escolaridade Após 2005 - Código        0
Qtd Hora Contr                         0
Idade                                  0
Vl Rem Dezembro Nom                 7397
CNAE 2.0 Subclasse - Codigo            0
Sexo - Código                          0
Tamanho Estabelecimento - Código       0
Tempo Emprego                          0
Tipo Vínculo - Código                  0
dtype: int64

In [20]:
amostra_10k["Vl Rem Dezembro Nom"].describe()

count      2603.000000
mean       5322.186585
std        9099.165540
min         455.400000
25%        2107.975000
50%        2997.750000
75%        5164.135000
max      163251.730000
Name: Vl Rem Dezembro Nom, dtype: float64

In [21]:
amostra_10k[
    "Ind Vínculo Ativo 31/12 - Código"
].value_counts(dropna=False)

Ind Vínculo Ativo 31/12 - Código
1    7480
0    2520
Name: count, dtype: int64

In [22]:
ativos = amostra_10k[
    amostra_10k["Ind Vínculo Ativo 31/12 - Código"] == 1
]

print(f"Vínculos ativos: {len(ativos):,}")

print(
    ativos["Vl Rem Dezembro Nom"]
    .isna()
    .value_counts()
)

Vínculos ativos: 7,480
Vl Rem Dezembro Nom
True     4943
False    2537
Name: count, dtype: int64

In [23]:
colunas_teste = colunas + ["Vl Rem Média Nom"] + ["Ind Trabalho Intermitente - Código"]

teste_rem = pd.read_csv(
    arquivo_rais,
    sep=",",
    encoding="latin1",
    usecols=colunas_teste,
    nrows=10_000
)

In [24]:
ativos_teste = teste_rem[
    teste_rem["Ind Vínculo Ativo 31/12 - Código"] == 1
]

ativos_teste[
    ["Vl Rem Dezembro Nom", "Vl Rem Média Nom"]
].isna().sum()

Vl Rem Dezembro Nom    4943
Vl Rem Média Nom          0
dtype: int64

In [25]:
ativos_teste[
    ["Vl Rem Dezembro Nom", "Vl Rem Média Nom"]
].describe()

       Vl Rem Dezembro Nom  Vl Rem Média Nom
count          2537.000000       7480.000000
mean           5419.767052       1733.325193
std            9194.685325       4844.635775
min             458.180000          0.000000
25%            2132.000000          0.000000
50%            3036.000000          0.000000
75%            5266.490000       2168.487500
max          163251.730000     128139.960000

In [26]:
pd.crosstab(
    ativos_teste["Vl Rem Dezembro Nom"].isna(),
    ativos_teste["Vl Rem Média Nom"].isna(),
    rownames=["Dezembro ausente"],
    colnames=["Média ausente"]
)

Média ausente     False
Dezembro ausente
False              2537
True               4943

In [27]:
pd.crosstab(
    ativos_teste["Ind Trabalho Intermitente - Código"],
    ativos_teste["Vl Rem Dezembro Nom"].isna(),
    margins=True
)

Vl Rem Dezembro Nom                 False  True   All
Ind Trabalho Intermitente - Código
0                                    2536  4636  7172
1                                       1   307   308
All                                  2537  4943  7480

## Critérios iniciais de preparação

A partir da documentação oficial da RAIS e da inspeção preliminar
dos microdados, foram definidos os seguintes critérios iniciais:

- considerar apenas vínculos ativos em 31/12/2025;
- tratar códigos classificados como ignorados (`-1`) como valores ausentes;
- utilizar a classificação oficial de escolaridade da RAIS;
- preservar inicialmente as categorias originais de escolaridade;
- utilizar a CNAE 2.0 para classificação da atividade econômica;
- investigar valores ausentes e valores iguais a zero nas variáveis
  de remuneração antes da definição da variável salarial principal;
- não excluir observações automaticamente sem justificativa
  documentada.

In [28]:
mapa_escolaridade = {
    1: "Analfabeto",
    2: "Até 5º ano incompleto",
    3: "5º ano completo do Fundamental",
    4: "6º ao 9º ano do Fundamental",
    5: "Fundamental completo",
    6: "Médio incompleto",
    7: "Médio completo",
    8: "Superior incompleto",
    9: "Superior completo",
    10: "Mestrado",
    11: "Doutorado"
}

In [30]:
ativos_teste = ativos_teste.copy()

ativos_teste["Escolaridade"] = (
    ativos_teste["Escolaridade Após 2005 - Código"]
    .map(mapa_escolaridade)
)

In [31]:
ativos_teste[
    "Escolaridade"
].value_counts(dropna=False)

Escolaridade
Médio completo                    3601
Superior completo                 2158
Fundamental completo               686
Médio incompleto                   325
6º ao 9º ano do Fundamental        238
Superior incompleto                172
5º ano completo do Fundamental     130
Até 5º ano incompleto              112
Analfabeto                          27
Mestrado                            22
Doutorado                            9
Name: count, dtype: int64

In [32]:
ativos_teste.groupby(
    "Escolaridade"
).agg(
    total=("Escolaridade", "size"),
    rem_dez_preenchida=("Vl Rem Dezembro Nom", "count")
)

                                total  rem_dez_preenchida
Escolaridade
5º ano completo do Fundamental    130                  26
6º ao 9º ano do Fundamental       238                  53
Analfabeto                         27                  10
Até 5º ano incompleto             112                  30
Doutorado                           9                   3
Fundamental completo              686                 127
Mestrado                           22                   9
Médio completo                   3601                1250
Médio incompleto                  325                 117
Superior completo                2158                 844
Superior incompleto               172                  68

In [33]:
diagnostico_rem = (
    ativos_teste
    .groupby("Tipo Vínculo - Código")
    .agg(
        total=("Tipo Vínculo - Código", "size"),
        com_rem_dez=("Vl Rem Dezembro Nom", "count"),
        rem_media=("Vl Rem Média Nom", "mean")
    )
)

diagnostico_rem["pct_com_rem_dez"] = (
    diagnostico_rem["com_rem_dez"]
    / diagnostico_rem["total"]
    * 100
)

diagnostico_rem.sort_values(
    "total",
    ascending=False
)

                       total  com_rem_dez    rem_media  pct_com_rem_dez
Tipo Vínculo - Código
10                      4850         1915  1940.301113        39.484536
30                       680          230  2760.335191        33.823529
40                       602           43   300.073289         7.142857
96                       472           26   327.396038         5.508475
80                       179           80  3557.990112        44.692737
35                       151           17   885.538675        11.258278
60                       135          114  2051.177037        84.444444
50                       119           14   256.435546        11.764706
25                        61            6   226.278689         9.836066
55                        50           33   705.773200        66.000000
15                        49            3   245.342245         6.122449
20                        44           19  1447.715000        43.181818
31                        39           23  2534.805641        58.974359
97                        23            8  1273.916957        34.782609
90                        18            6   645.408889        33.333333
75                         6            0     0.000000         0.000000
95                         2            0     0.000000         0.000000

In [34]:
ativos_teste[
    "Vl Rem Média Nom"
].eq(0).value_counts()

Vl Rem Média Nom
True     4704
False    2776
Name: count, dtype: int64

In [35]:
ativos_teste.loc[
    ativos_teste["Vl Rem Média Nom"] == 0,
    [
        "Tipo Vínculo - Código",
        "Ind Trabalho Intermitente - Código",
        "Qtd Hora Contr",
        "Tempo Emprego",
        "Vl Rem Dezembro Nom"
    ]
].head(20)

,Tipo Vínculo - Código,Ind Trabalho Intermitente - Código,Qtd Hora Contr,Tempo Emprego,Vl Rem Dezembro Nom
0,10,1,99,18.9,NaN
1,10,0,40,59.0,NaN
2,10,0,44,26.0,NaN
4,10,0,44,38.9,NaN
5,10,0,44,75.8,NaN
7,10,0,44,24.0,NaN
8,10,0,44,156.4,NaN
9,10,0,44,35.0,NaN
10,10,1,44,3.0,NaN
14,10,0,44,76.5,NaN
15,10,0,0,38.4,NaN
16,10,0,44,383.0,NaN
17,10,0,36,414.4,NaN
18,10,0,44,215.3,NaN
20,10,0,0,191.0,NaN
21,50,0,44,20.0,NaN
23,10,0,44,7.7,NaN
24,10,0,44,77.0,NaN
25,10,1,44,39.1,NaN
26,10,0,28,59.8,NaN

In [36]:
colunas_meses = [
    "Vl Rem Janeiro SC",
    "Vl Rem Fevereiro SC",
    "Vl Rem Março SC",
    "Vl Rem Abril SC",
    "Vl Rem Maio SC",
    "Vl Rem Junho SC",
    "Vl Rem Julho SC",
    "Vl Rem Agosto SC",
    "Vl Rem Setembro SC",
    "Vl Rem Outubro SC",
    "Vl Rem Novembro SC"
]

In [37]:
teste_meses = pd.read_csv(
    arquivo_rais,
    sep=",",
    encoding="latin1",
    usecols=[
        "Ind Vínculo Ativo 31/12 - Código",
        "Vl Rem Dezembro Nom",
        "Vl Rem Média Nom",
        *colunas_meses
    ],
    nrows=10_000
)

ativos_meses = teste_meses[
    teste_meses["Ind Vínculo Ativo 31/12 - Código"] == 1
].copy()

In [38]:
ativos_meses[colunas_meses].describe().T

,count,mean,std,min,25%,50%,75%,max
Vl Rem Janeiro SC,7480.0,1417.137829,5238.901770,-215.26,0.0,0.0,0.0000,140080.20
Vl Rem Fevereiro SC,7480.0,1766.034811,27317.662668,-75.79,0.0,0.0,457.7475,2223144.43
Vl Rem Março SC,7480.0,1519.899353,6828.734434,0.00,0.0,0.0,1154.9450,358772.35
Vl Rem Abril SC,7480.0,1544.069568,6025.467057,-140.20,0.0,0.0,1507.7550,253720.23
Vl Rem Maio SC,7480.0,1645.383707,6951.556287,-450.21,0.0,0.0,1694.8225,298177.86
Vl Rem Junho SC,7480.0,1594.125834,5147.336398,-2648.70,0.0,0.0,1808.1750,120523.00
Vl Rem Julho SC,7480.0,1683.672070,5351.177714,0.00,0.0,0.0,1916.5500,126766.00
Vl Rem Agosto SC,7480.0,1690.957513,5346.609845,-177.00,0.0,0.0,1976.3900,126766.00
Vl Rem Setembro SC,7480.0,1735.091924,5319.988382,0.00,0.0,0.0,2028.9475,126766.00
Vl Rem Outubro SC,7480.0,1791.285171,5922.934313,-0.01,0.0,0.0,2104.8975,207440.46
Vl Rem Novembro SC,7480.0,1830.606969,5732.807825,0.00,0.0,0.0,2185.9950,127970.00

In [39]:
sem_rem_dez = ativos_meses[
    ativos_meses["Vl Rem Dezembro Nom"].isna()
]

sem_rem_dez[colunas_meses].describe().T

,count,mean,std,min,25%,50%,75%,max
Vl Rem Janeiro SC,4943.0,137.855588,1422.637031,-215.26,0.0,0.0,0.0,61372.88
Vl Rem Fevereiro SC,4943.0,588.608343,31652.628312,0.00,0.0,0.0,0.0,2223144.43
Vl Rem Março SC,4943.0,140.816601,1476.769866,0.00,0.0,0.0,0.0,61372.88
Vl Rem Abril SC,4943.0,134.218299,1438.325084,-140.20,0.0,0.0,0.0,61372.88
Vl Rem Maio SC,4943.0,170.143617,1590.232724,-450.21,0.0,0.0,0.0,64748.39
Vl Rem Junho SC,4943.0,144.117174,1285.255134,-2648.70,0.0,0.0,0.0,43633.30
Vl Rem Julho SC,4943.0,141.140585,1227.725168,0.00,0.0,0.0,0.0,41181.37
Vl Rem Agosto SC,4943.0,136.794012,1202.382113,-177.00,0.0,0.0,0.0,41483.49
Vl Rem Setembro SC,4943.0,136.384370,1215.337258,0.00,0.0,0.0,0.0,41512.99
Vl Rem Outubro SC,4943.0,118.945792,1094.309708,-0.01,0.0,0.0,0.0,41512.99
Vl Rem Novembro SC,4943.0,89.397044,950.294225,0.00,0.0,0.0,0.0,41394.99

In [40]:
pd.crosstab(
    ativos_teste["Vl Rem Dezembro Nom"].isna(),
    ativos_teste["Vl Rem Média Nom"] == 0,
    rownames=["Remuneração dezembro ausente"],
    colnames=["Remuneração média = 0"],
    margins=True
)

Remuneração média = 0         False  True   All
Remuneração dezembro ausente
False                          2537     0  2537
True                            239  4704  4943
All                            2776  4704  7480